package com.example.demo.controller;

import java.util.Optional;

import com.example.demo.entity.User;
import com.example.demo.repository.UserRepository;
import com.example.demo.service.api.UserService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private UserService service1;

  @Autowired
  private UserService service2;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody User addNewUser (@RequestParam String name
      , @RequestParam String email) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    return Optional.of(service1.save(name, email)).orElse(new User());
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<User> getAllUsers() {
    // This returns a JSON or XML with the users
    return service1.getAll();
  }

  @GetMapping(path="/all2")
  public @ResponseBody Iterable<User> getAllUsers2() {
    // This returns a JSON or XML with the users
    return service2.getAll();
  }

  @GetMapping(path="/byId")
  public @ResponseBody User getUserById(@RequestParam Integer id) {
    // This returns a JSON or XML with the users
    return service1.getById(id);
  }
}